<?php
/**
 * Created by PhpStorm.
 * Author: npbtrac@yahoo.com
 * Date time: 12/16/17 12:09 PM
 */

namespace Enpii\WpEnpiiCore\Base;


class App extends BaseApp {
	/** @property static $instance */
	public static $instance;

	public static function initInstance($config = null) {
		if ( empty( static::$container ))   {
			static::$container = new Container($config);
		}

		if ( ! empty( $config ) && empty(static::$instance) ) {
			static::$instance = new static( $config );
		}
	}

	public function getComponent( $alias ) {
		return App::$container->getComponent( $alias ); // TODO: Change the autogenerated stub
	}
}