<?php
/**
 * Created by PhpStorm.
 * Author: npbtrac@yahoo.com
 * Date time: 12/21/17 1:21 PM
 */

namespace Enpii\WpEnpiiCore\Base;


class BaseApp {
	/* @var Container $container */
	public static $container;

	/* @var static $instance */
	public static $instance;

	protected $_components = [];
	protected $_config = null;

	public function __construct( $config = null ) {


	}

	/**
	 * Initialize a singleton application instance
	 *
	 * @param null|array $config
	 */
	public static function init_instance( $config = null ) {
		if ( empty( static::$container ) ) {
			static::$container = new Container( $config );
		}

		if ( ! empty( $config ) && empty( static::$instance ) ) {
			static::$instance = new static( $config );
		}
	}

	/**
	 * Call a component inside it's container
	 *
	 * @param $alias
	 *
	 * @return mixed|null
	 */
	public function get_component( $alias ) {
		return static::$container->get_component( $alias ); // TODO: Change the autogenerated stub
	}
}